---
periods: 3
window_size: 2016
init_difficulty: 1
expected_block_time: 10  # in min
debug: false
export_graphs: false

# multiple miners will equally split alpha parameter
# multiple definitions of same "type" of miner allowed to explicitly define the alpha param
# types: honest, selfish
agents:
  agent1:
    honest:
      num: 1
      alpha: 0.9
      gamma: 0.80
  agent2:
    selfish:
      num: 1
      alpha: 0.1
      gamma: 0.20