---
num_blocks: 1000
debug: false
export_graphs: true
# multiple miners will equally split alpha parameter
# multiple definitions of same "type" of miner allowed to explicitly define the alpha param
# types: honest, selfish
miners:
  honest:
    num: 1
    alpha: 0.3
    gamma: 0.4
  selfish:
    num: 1
    alpha: .7
    gamma: 0.6
